### ISSUE TITLE
This will exclude special files like `/dev/null` or `/dev/stdin` and other similar (kernel) files. Don't make the same "mistake" I did :(

### ISSUE THREAD

**Issue by csicar** [compilerpraktikum/compiler#55]
This will exclude special files like `/dev/null` or `/dev/stdin` and other similar (kernel) files. Don't make the same "mistake" I did :(

_Originally posted by @I-Al-Istannen in https://github.com/compilerpraktikum/compiler/pull/49#discussion_r748900957_

**Comment by iTob191** [comment]
Solved by 674c983f83e9251d3535904885f4d6384bc434d7
