### ISSUE TITLE
This has a race condition with file deletion / permission settings etc anyways, so the checks above are just to provide nicer messages. You still need to handle all errors when trying to read from the file and *that* is where your "is regular file" check should be: implicitly done by the standardlib. If you use NIO.2, the error messages are useful and descriptive and cover the cases above nicely.

### ISSUE THREAD

**Issue by csicar** [compilerpraktikum/compiler#56]
This has a race condition with file deletion / permission settings etc anyways, so the checks above are just to provide nicer messages. You still need to handle all errors when trying to read from the file and *that* is where your "is regular file" check should be: implicitly done by the standardlib. If you use NIO.2, the error messages are useful and descriptive and cover the cases above nicely.

_Originally posted by @I-Al-Istannen in https://github.com/compilerpraktikum/compiler/pull/49#discussion_r748901086_

**Comment by iTob191** [comment]
Solved by 674c983f83e9251d3535904885f4d6384bc434d7
