### ISSUE TITLE
Neue Parser/PrettyPrinter-Tests schlagen fehl

### ISSUE THREAD

**Issue by RobinRSchulz** [compilerpraktikum/compiler#85]
Auf feature/type_analysis ham wir den MJ-Tests-Stand aktualisiert, um die semantic tests zu bekommen und da ist ein Test dabei, der fehlschlägt:
OpeningComment.invalid.mj

Muss man sich irgendwann mal anschauen.

**Comment by iTob191** [comment]
Seems to be fixed.
