### ISSUE TITLE
Utility Functions vereinigen

### ISSUE THREAD

**Issue by Cydhra** [compilerpraktikum/compiler#86]
Es gibt gefühlt 300 verschiedene Funktionen um etwas am AST zu checken und im Fehlerfall nen Error auszugeben. Die könnte man mal alle in eine elegante Lösung vereinigen.

Auch sonstige Utilities kann man dabei mal auf Redundanz checken.

**Comment by iTob191** [comment]
Teilweise in #88 gefixt
