### ISSUE TITLE
Failing Tests finden & fixen @csicar

### ISSUE THREAD

**Issue by csicar** [compilerpraktikum/compiler#93]
- [x] nimmt 01 als syntaktisch korrekten Ausdruck an und behält nur 0
- [x] nicht-statische Methode main kann nicht aufgerufen werden
- [x] System.out.println(new A().bla(new A()));, bla gibt A zurück
- [x] Fehlermeldung von System.out.println(new A()) gibt unformatierte Compiler-Objekte aus

**Comment by Cydhra** [comment]
```
class Bait {
    public int[] Z;

    public static void main(String[] args) {

    }

    public Bait test(int x) {
        return Z[3];
    }
}
```

wird nicht abgelehnt. Kann sein, dass das mit dem `new A()` zeug von oben zusammenhängt, aber prüf mal nach.

**Comment by csicar** [comment]
Sieht so aus, als wäre das problem schon gelöst: https://github.com/compilerpraktikum/compiler/pull/94/files#diff-0af8126dcb351b1ecbee23df82dc9a98c7e38a45f6d8113b32ede1aa4d9acdf9R269
